# Generated by Django 3.1.3 on 2021-07-12 22:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210712_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='Day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=56),
        ),
    ]
