# Generated by Django 3.1.3 on 2021-07-12 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210712_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='days_available',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.days'),
        ),
    ]
