# Generated by Django 3.1.3 on 2021-07-12 23:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_spot_days_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='days_available',
        ),
        migrations.AddField(
            model_name='spot',
            name='day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Every Day', 'Every Day')], default='Every Day', max_length=66),
        ),
        migrations.DeleteModel(
            name='Days',
        ),
    ]
