# Generated by Django 3.1.3 on 2021-07-13 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210712_2324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='VehicleType',
        ),
        migrations.RenameField(
            model_name='spot',
            old_name='category',
            new_name='Types_of_Vehicle',
        ),
    ]
