# Generated by Django 3.1.3 on 2021-07-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='day',
            new_name='Days_Available',
        ),
        migrations.RenameField(
            model_name='spot',
            old_name='spot_phone',
            new_name='contact_phone',
        ),
        migrations.RenameField(
            model_name='spot',
            old_name='spot_name',
            new_name='landlord_name',
        ),
    ]
