# Generated by Django 3.1.3 on 2021-07-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210715_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='landlord_name',
            new_name='Landlord_name',
        ),
        migrations.RenameField(
            model_name='spot',
            old_name='contact_phone',
            new_name='phone_number',
        ),
    ]
