# Generated by Django 3.1.3 on 2021-07-17 17:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210716_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='Times_Available',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('8pm-9pm', '8am-9am'), ('9pm-10pm', '9am-10am'), ('10pm-11pm', '10am-11am'), ('11pm-12pm', '11am-12am'), ('12am-1pm', '12am-1pm'), ('1pm-2pm', '1pm-2pm'), ('2pm-3pm', '2pm-3pm'), ('3pm-4pm', '3pm-4pm'), ('4pm-5pm', '4pm-5pm'), ('5pm-6pm', '5pm-6pm'), ('6pm-7pm', '6pm-7pm'), ('7pm-8pm', '7pm-8pm'), ('8pm-9pm', '8pm-9pm'), ('9pm-10pm', '9pm-10pm'), ('10pm-11pm', '10pm-11pm'), ('11pm-12pm', '11pm-12pm'), ('All Day', 'All Day')], default='All Day', max_length=146),
        ),
    ]
