# Generated by Django 3.1.3 on 2021-07-17 19:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_auto_20210717_1905'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='host',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='spot',
            old_name='host',
            new_name='user',
        ),
    ]
