# Generated by Django 3.1.3 on 2021-07-20 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_auto_20210717_1933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='spot',
            old_name='user',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='spot',
            old_name='quantity',
            new_name='individuals',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='Days_Available',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='Times_Available',
        ),
        migrations.AlterField(
            model_name='spot',
            name='status',
            field=models.CharField(choices=[('creating', 'creating'), ('processing', 'Processing'), ('completed', 'Completed'), ('unavailable', 'Unavailable'), ('available', 'Available'), ('canceled', 'Canceled')], default='creating', max_length=20),
        ),
    ]
