# Generated by Django 3.1.3 on 2021-07-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210720_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='spot_lat',
            new_name='end_lat',
        ),
        migrations.RenameField(
            model_name='spot',
            old_name='spot_lng',
            new_name='end_lng',
        ),
        migrations.RenameField(
            model_name='spot',
            old_name='Landlord_name',
            new_name='end_point',
        ),
        migrations.RenameField(
            model_name='spot',
            old_name='spot_address',
            new_name='origin_point',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='license_photo',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='spot',
            name='end_photo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='origin_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='origin_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='spot',
            name='origin_lng',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='spot',
            name='origin_photo',
            field=models.ImageField(blank=True, null=True, upload_to='spot/origin_photos/'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='status',
            field=models.CharField(choices=[('creating', 'Creating'), ('processing', 'Processing'), ('driver en route', 'Driver en route'), ('picked up', 'Picked up'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='creating', max_length=20),
        ),
    ]
