# Generated by Django 3.1.3 on 2021-07-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210721_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='end_photo',
            field=models.ImageField(blank=True, null=True, upload_to='spot/end_photos/'),
        ),
    ]
