# Generated by Django 3.1.3 on 2021-07-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210721_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='origin_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
