# Generated by Django 3.1.3 on 2021-07-21 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_spot_origin_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='origin_description',
        ),
    ]
