# Generated by Django 3.1.3 on 2021-07-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_spot_origin_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='name',
        ),
        migrations.AddField(
            model_name='spot',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='spot',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
