# Generated by Django 3.1.3 on 2021-07-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210721_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='individuals',
        ),
        migrations.AddField(
            model_name='spot',
            name='Guests',
            field=models.IntegerField(default=0),
        ),
    ]
