# Generated by Django 3.1.3 on 2021-07-22 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210722_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='Guests',
            new_name='Number_of_Guest',
        ),
    ]
